#version: '3.9'
#services:
#  server:
#    build: ./
#    command: ./app
#    ports:
#      - 8080:8080
#  db:
#    restart: always
#    image: postgres:16
#    volumes:
#      - //c//Program Files//PostgreSQL//16//data
#    environment:
#      POSTGRES_USER: vetkz
#      POSTGRES_PASSWORD: mycode
#      POSTGRES_DB: postgres
#      POSTGRES_HOST: vetkz
#    ports:
#      - 5432:5432
################################
version: '3'
services:
  app:
    build: ./
    command: ./wait-for-postgres.sh postgres ./main
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD = mycode

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: vetkz
      POSTGRES_USER: vetkz
      POSTGRES_PASSWORD: mycode
    ports:
      - "5432:5432"